# Generated by Django 4.2.5 on 2024-03-13 05:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0005_category_job_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
