# Generated by Django 4.2.5 on 2024-03-13 05:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0006_remove_job_category_delete_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recruiter",
            name="image",
        ),
    ]
