# Generated by Django 4.2.5 on 2024-04-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0008_recruiter_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("about", models.TextField()),
                ("age", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("skills", models.TextField()),
                ("education", models.TextField()),
                ("languages", models.TextField()),
                ("projects", models.TextField()),
                ("experience", models.TextField()),
                ("achievements", models.TextField()),
            ],
        ),
    ]
